# Generated by Django 4.2.7 on 2024-06-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pic/default.png', null=True, upload_to='profile_pic'),
        ),
    ]
