# Generated by Django 4.2.7 on 2024-06-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_bio_alter_profile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Bio', max_length=400, null=True),
        ),
    ]
